-- Phase 6–7: insurance providers/plans/coverage + médecin enrichissement.
-- Does not modify V1–V9.

CREATE TABLE IF NOT EXISTS insurance_providers (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(64)  NOT NULL,
    nom     VARCHAR(255) NOT NULL,
    actif   BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_insurance_providers_code ON insurance_providers (code);

CREATE TABLE IF NOT EXISTS insurance_plans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT       NOT NULL REFERENCES insurance_providers (id),
    code        VARCHAR(64)  NOT NULL,
    libelle     VARCHAR(255) NOT NULL,
    actif       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_insurance_plans_provider_code
    ON insurance_plans (provider_id, code);
CREATE INDEX IF NOT EXISTS idx_insurance_plans_provider ON insurance_plans (provider_id);

CREATE TABLE IF NOT EXISTS coverage_rules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id         BIGINT         NOT NULL REFERENCES insurance_plans (id),
    taux_percent    NUMERIC(5, 2)  NOT NULL DEFAULT 0,
    plafond         NUMERIC(12, 2),
    modalite        VARCHAR(32),
    catalogue_id    BIGINT REFERENCES catalogue_examens (id)
);

CREATE INDEX IF NOT EXISTS idx_coverage_rules_plan ON coverage_rules (plan_id);
CREATE INDEX IF NOT EXISTS idx_coverage_rules_catalogue ON coverage_rules (catalogue_id);

ALTER TABLE patients
    ADD COLUMN IF NOT EXISTS insurance_plan_id BIGINT NULL REFERENCES insurance_plans (id);

CREATE INDEX IF NOT EXISTS idx_patients_insurance_plan ON patients (insurance_plan_id);

ALTER TABLE medecins_referents
    ADD COLUMN IF NOT EXISTS etablissement VARCHAR(255),
    ADD COLUMN IF NOT EXISTS actif BOOLEAN NOT NULL DEFAULT TRUE;
