-- Phase 10: imaging metadata only (no DICOM BLOB). Does not modify V1–V10.

CREATE TABLE IF NOT EXISTS imaging_studies (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id          BIGINT NOT NULL REFERENCES patients (id),
    examen_id           BIGINT REFERENCES examens (id),
    study_instance_uid  VARCHAR(128),
    modality            VARCHAR(16),
    study_description   VARCHAR(512),
    study_date          VARCHAR(32),
    number_of_images    INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_imaging_studies_patient ON imaging_studies (patient_id);
CREATE INDEX IF NOT EXISTS idx_imaging_studies_examen ON imaging_studies (examen_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_imaging_studies_uid
    ON imaging_studies (study_instance_uid)
    WHERE study_instance_uid IS NOT NULL;

CREATE TABLE IF NOT EXISTS imaging_series (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id             BIGINT NOT NULL REFERENCES imaging_studies (id),
    series_instance_uid  VARCHAR(128),
    series_description   VARCHAR(512),
    modality             VARCHAR(16),
    number_of_instances  INTEGER NOT NULL DEFAULT 0,
    thumbnail_url        VARCHAR(1024),
    series_number        INTEGER
);

CREATE INDEX IF NOT EXISTS idx_imaging_series_study ON imaging_series (study_id);

CREATE TABLE IF NOT EXISTS imaging_instances (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id           BIGINT NOT NULL REFERENCES imaging_series (id),
    sop_instance_uid    VARCHAR(128),
    instance_number     INTEGER,
    wado_uri            VARCHAR(1024)
);

CREATE INDEX IF NOT EXISTS idx_imaging_instances_series ON imaging_instances (series_id);
