-- Phase 12–14: RBAC aliases + notifications + perf indexes. Does not modify V1–V11.

CREATE TABLE IF NOT EXISTS role_aliases (
    backend_role    VARCHAR(64) NOT NULL,
    ui_role         VARCHAR(64) NOT NULL,
    PRIMARY KEY (backend_role, ui_role)
);

INSERT INTO role_aliases (backend_role, ui_role) VALUES
    ('DIRECTEUR', 'DIRECTEUR'),
    ('DIRECTEUR', 'DIRECTION'),
    ('DIRECTEUR', 'ADMIN'),
    ('DIRECTEUR', 'SUPER_ADMIN'),
    ('RADIOLOGUE', 'RADIOLOGUE'),
    ('MANIPULATEUR', 'MANIPULATEUR'),
    ('MANIPULATEUR', 'TECHNICIEN'),
    ('SECRETARIAT', 'SECRETARIAT'),
    ('SECRETARIAT', 'SECRETAIRE'),
    ('SECRETARIAT', 'ACCUEIL'),
    ('SECRETARIAT', 'CAISSIER'),
    ('SECRETARIAT', 'COMPTABLE'),
    ('SECRETARIAT', 'AUDITEUR')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS notification_templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64) NOT NULL,
    channel     VARCHAR(32) NOT NULL,
    subject     VARCHAR(255),
    body        TEXT NOT NULL,
    actif       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_notification_templates_code_channel
    ON notification_templates (code, channel);

CREATE TABLE IF NOT EXISTS notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code   VARCHAR(64),
    channel         VARCHAR(32) NOT NULL,
    recipient       VARCHAR(255) NOT NULL,
    subject         VARCHAR(255),
    body            TEXT NOT NULL,
    status          VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    entity_type     VARCHAR(64),
    entity_id       VARCHAR(64),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at         TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_notifications_status ON notifications (status, created_at);

CREATE TABLE IF NOT EXISTS notification_attempts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id     BIGINT NOT NULL REFERENCES notifications (id),
    attempt_no          INTEGER NOT NULL DEFAULT 1,
    status              VARCHAR(32) NOT NULL,
    error_message       VARCHAR(1024),
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notification_attempts_notif
    ON notification_attempts (notification_id, created_at);

CREATE INDEX IF NOT EXISTS idx_patients_nom_complet ON patients (nom_complet);
CREATE INDEX IF NOT EXISTS idx_invoices_issued_at ON invoices (issued_at);
