-- Catalogue extensions (Moroccan market baseline) + Excel import history + demo markers.
-- Does not modify V1–V14. Prices are indicative demo baselines, not official ANAM tariffs.

ALTER TABLE catalogue_examens
    ADD COLUMN IF NOT EXISTS body_region VARCHAR(64),
    ADD COLUMN IF NOT EXISTS contrast_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS contrast_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS sedation_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS currency VARCHAR(8) NOT NULL DEFAULT 'MAD',
    ADD COLUMN IF NOT EXISTS national_reference_price NUMERIC(10, 2),
    ADD COLUMN IF NOT EXISTS reference_source VARCHAR(128),
    ADD COLUMN IF NOT EXISTS reference_date DATE,
    ADD COLUMN IF NOT EXISTS market_indicative BOOLEAN NOT NULL DEFAULT TRUE;

COMMENT ON COLUMN catalogue_examens.prix IS 'Centre selling price (MAD). Editable.';
COMMENT ON COLUMN catalogue_examens.national_reference_price IS 'Optional national/reference tariff — never invent official ANAM values.';
COMMENT ON COLUMN catalogue_examens.market_indicative IS 'True when prix is a market demo baseline, not a contractual centre tariff.';

CREATE TABLE IF NOT EXISTS data_import_jobs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename        VARCHAR(512) NOT NULL,
    import_type     VARCHAR(64) NOT NULL,
    import_mode     VARCHAR(32) NOT NULL DEFAULT 'INITIALIZATION',
    status          VARCHAR(32) NOT NULL,
    rows_total      INTEGER NOT NULL DEFAULT 0,
    rows_valid      INTEGER NOT NULL DEFAULT 0,
    rows_imported   INTEGER NOT NULL DEFAULT 0,
    rows_rejected   INTEGER NOT NULL DEFAULT 0,
    error_summary   TEXT,
    created_by_id   BIGINT REFERENCES utilisateurs (id),
    created_by_name VARCHAR(255),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_data_import_jobs_created ON data_import_jobs (created_at DESC);

CREATE TABLE IF NOT EXISTS demo_dataset_markers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(64) NOT NULL,
    entity_id   VARCHAR(64) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_demo_marker UNIQUE (entity_type, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_demo_markers_type ON demo_dataset_markers (entity_type);
