-- RBAC, audit immuable, idempotence, colonnes métier sur patients/examens/utilisateurs.

-- ========== utilisateurs (soft lock, audit champs) ==========
ALTER TABLE utilisateurs
    ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS locked_until TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP(6);

-- ========== patients 360 ==========
ALTER TABLE patients
    ADD COLUMN IF NOT EXISTS nom VARCHAR(120),
    ADD COLUMN IF NOT EXISTS prenom VARCHAR(120),
    ADD COLUMN IF NOT EXISTS numero_dossier VARCHAR(32),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS created_by_id BIGINT REFERENCES utilisateurs (id),
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0;

UPDATE patients
SET nom = COALESCE(nom, NULLIF(split_part(TRIM(nom_complet), ' ', 1), '')),
    prenom = COALESCE(
        prenom,
        NULLIF(TRIM(substring(TRIM(nom_complet) from length(split_part(TRIM(nom_complet), ' ', 1)) + 1)), '')
    )
WHERE nom_complet IS NOT NULL AND nom IS NULL;

UPDATE patients
SET numero_dossier = 'PAT-' || LPAD(id::text, 6, '0')
WHERE numero_dossier IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_patients_numero_dossier ON patients (numero_dossier);
CREATE INDEX IF NOT EXISTS idx_patients_cin ON patients (cin);
CREATE INDEX IF NOT EXISTS idx_patients_telephone ON patients (telephone);
CREATE INDEX IF NOT EXISTS idx_patients_nom_prenom ON patients (LOWER(nom), LOWER(prenom));
CREATE INDEX IF NOT EXISTS idx_patients_date_naissance ON patients (date_naissance);
CREATE INDEX IF NOT EXISTS idx_patients_num_affiliation ON patients (num_affiliation);
CREATE INDEX IF NOT EXISTS idx_patients_deleted_at ON patients (deleted_at);

-- ========== examens / workflow ==========
ALTER TABLE examens
    ADD COLUMN IF NOT EXISTS workflow_status VARCHAR(32) NOT NULL DEFAULT 'SCHEDULED',
    ADD COLUMN IF NOT EXISTS priorite VARCHAR(16) NOT NULL DEFAULT 'ROUTINE',
    ADD COLUMN IF NOT EXISTS exam_type_code VARCHAR(64),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS created_by_id BIGINT REFERENCES utilisateurs (id),
    ADD COLUMN IF NOT EXISTS assigned_radiologue_id BIGINT REFERENCES utilisateurs (id),
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0;

UPDATE examens SET workflow_status = CASE etat_patient
    WHEN 'attendu' THEN 'SCHEDULED'
    WHEN 'arrive' THEN 'ARRIVED'
    WHEN 'retard' THEN 'WAITING'
    WHEN 'attente_longue' THEN 'WAITING'
    ELSE 'SCHEDULED'
END
WHERE workflow_status = 'SCHEDULED';

CREATE INDEX IF NOT EXISTS idx_examens_date ON examens (date_examen);
CREATE INDEX IF NOT EXISTS idx_examens_statut ON examens (etat_patient);
CREATE INDEX IF NOT EXISTS idx_examens_workflow ON examens (workflow_status);
CREATE INDEX IF NOT EXISTS idx_examens_modalite ON examens (modalite);
CREATE INDEX IF NOT EXISTS idx_examens_patient ON examens (patient_id);
CREATE INDEX IF NOT EXISTS idx_examens_prescripteur ON examens (prescripteur_id);
CREATE INDEX IF NOT EXISTS idx_examens_radiologue ON examens (assigned_radiologue_id);

CREATE TABLE IF NOT EXISTS exam_status_history (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examen_id           BIGINT NOT NULL REFERENCES examens (id),
    from_status         VARCHAR(32),
    to_status           VARCHAR(32) NOT NULL,
    actor_id            BIGINT REFERENCES utilisateurs (id),
    actor_name          VARCHAR(255),
    reason              VARCHAR(500),
    created_at          TIMESTAMP(6) NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_exam_status_history_examen ON exam_status_history (examen_id, created_at);

-- ========== RBAC ==========
CREATE TABLE IF NOT EXISTS roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(32) NOT NULL UNIQUE,
    label       VARCHAR(80) NOT NULL,
    system_role BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64) NOT NULL UNIQUE,
    label       VARCHAR(120) NOT NULL,
    domain      VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id         BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id   BIGINT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id     BIGINT NOT NULL REFERENCES utilisateurs (id) ON DELETE CASCADE,
    role_id     BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

INSERT INTO roles (code, label) VALUES
    ('SUPER_ADMIN', 'Super administrateur'),
    ('ADMIN', 'Administrateur'),
    ('DIRECTION', 'Direction'),
    ('ACCUEIL', 'Accueil'),
    ('SECRETAIRE', 'Secrétaire'),
    ('RADIOLOGUE', 'Radiologue'),
    ('MANIPULATEUR', 'Manipulateur'),
    ('CAISSIER', 'Caissier'),
    ('COMPTABLE', 'Comptable'),
    ('AUDITEUR', 'Auditeur')
ON CONFLICT (code) DO NOTHING;

INSERT INTO permissions (code, label, domain) VALUES
    ('PATIENT_READ', 'Lire un patient', 'PATIENT'),
    ('PATIENT_CREATE', 'Créer un patient', 'PATIENT'),
    ('PATIENT_UPDATE', 'Modifier un patient', 'PATIENT'),
    ('EXAM_READ', 'Lire un examen', 'EXAM'),
    ('EXAM_CREATE', 'Créer un examen', 'EXAM'),
    ('EXAM_UPDATE', 'Modifier un examen', 'EXAM'),
    ('WORKLIST_ASSIGN', 'Assigner un examen', 'EXAM'),
    ('REPORT_READ', 'Lire un compte-rendu', 'REPORT'),
    ('REPORT_WRITE', 'Rédiger un compte-rendu', 'REPORT'),
    ('REPORT_VALIDATE', 'Valider un compte-rendu', 'REPORT'),
    ('REPORT_AMEND', 'Amender un compte-rendu', 'REPORT'),
    ('INVOICE_READ', 'Lire une facture', 'INVOICE'),
    ('INVOICE_CREATE', 'Créer une facture', 'INVOICE'),
    ('PAYMENT_CREATE', 'Enregistrer un paiement', 'INVOICE'),
    ('AUDIT_READ', 'Lire l''audit', 'AUDIT'),
    ('FRAUD_REVIEW', 'Traiter une alerte fraude', 'FRAUD'),
    ('USER_MANAGE', 'Gérer les utilisateurs', 'SECURITY')
ON CONFLICT (code) DO NOTHING;

-- Matrice : DIRECTION / SUPER_ADMIN / ADMIN = tout
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.code IN ('SUPER_ADMIN', 'ADMIN', 'DIRECTION')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'PATIENT_READ', 'PATIENT_CREATE', 'PATIENT_UPDATE',
    'EXAM_READ', 'EXAM_CREATE', 'EXAM_UPDATE',
    'INVOICE_READ', 'INVOICE_CREATE'
)
WHERE r.code IN ('ACCUEIL', 'SECRETAIRE')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'PATIENT_READ', 'EXAM_READ', 'EXAM_UPDATE', 'WORKLIST_ASSIGN',
    'REPORT_READ', 'REPORT_WRITE', 'REPORT_VALIDATE', 'REPORT_AMEND'
)
WHERE r.code = 'RADIOLOGUE'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'PATIENT_READ', 'EXAM_READ', 'EXAM_UPDATE', 'WORKLIST_ASSIGN'
)
WHERE r.code = 'MANIPULATEUR'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'PATIENT_READ', 'INVOICE_READ', 'INVOICE_CREATE', 'PAYMENT_CREATE'
)
WHERE r.code = 'CAISSIER'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN ('PATIENT_READ', 'INVOICE_READ')
WHERE r.code = 'COMPTABLE'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'PATIENT_READ', 'EXAM_READ', 'REPORT_READ', 'INVOICE_READ', 'AUDIT_READ', 'FRAUD_REVIEW'
)
WHERE r.code = 'AUDITEUR'
ON CONFLICT DO NOTHING;

-- Mapping des rôles historiques (colonne utilisateurs.role) vers la table roles
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM utilisateurs u
JOIN roles r ON r.code = CASE u.role
    WHEN 'DIRECTEUR' THEN 'DIRECTION'
    WHEN 'SECRETARIAT' THEN 'ACCUEIL'
    ELSE u.role
END
ON CONFLICT DO NOTHING;

-- ========== audit immuable ==========
CREATE TABLE IF NOT EXISTS audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action          VARCHAR(64) NOT NULL,
    entity_type     VARCHAR(64),
    entity_id       VARCHAR(64),
    user_id         BIGINT,
    user_email      VARCHAR(255),
    ip_address      VARCHAR(64),
    correlation_id  VARCHAR(64),
    metadata        JSONB,
    before_state    JSONB,
    after_state     JSONB,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs (action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS security_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type      VARCHAR(64) NOT NULL,
    email           VARCHAR(255),
    ip_address      VARCHAR(64),
    success         BOOLEAN NOT NULL,
    detail          VARCHAR(500),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_security_events_email ON security_events (email, created_at DESC);

CREATE OR REPLACE FUNCTION prevent_audit_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Les journaux d''audit sont immuables';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS audit_logs_no_update ON audit_logs;
CREATE TRIGGER audit_logs_no_update
    BEFORE UPDATE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();

DROP TRIGGER IF EXISTS audit_logs_no_delete ON audit_logs;
CREATE TRIGGER audit_logs_no_delete
    BEFORE DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();

DROP TRIGGER IF EXISTS security_events_no_update ON security_events;
CREATE TRIGGER security_events_no_update
    BEFORE UPDATE ON security_events
    FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();

DROP TRIGGER IF EXISTS security_events_no_delete ON security_events;
CREATE TRIGGER security_events_no_delete
    BEFORE DELETE ON security_events
    FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();

-- ========== idempotence ==========
CREATE TABLE IF NOT EXISTS idempotency_keys (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key     VARCHAR(128) NOT NULL,
    user_id             BIGINT,
    request_hash        VARCHAR(64) NOT NULL,
    response_status     INTEGER,
    response_body       TEXT,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    expires_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_idempotency_key_user UNIQUE (idempotency_key, user_id)
);

CREATE INDEX IF NOT EXISTS idx_idempotency_expires ON idempotency_keys (expires_at);
