-- RIS operations: catalog, deposits, dossier tracking, payment ledger, documents.
-- No seed of exam prices or appointments. Existing examens keep montant/paiement.

CREATE TABLE IF NOT EXISTS catalogue_examens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom             VARCHAR(255) NOT NULL,
    code            VARCHAR(64),
    modalite        VARCHAR(32)  NOT NULL,
    categorie       VARCHAR(64),
    duree_minutes   INTEGER,
    prix            NUMERIC(10, 2) NOT NULL DEFAULT 0,
    description     TEXT,
    preparation     TEXT,
    actif           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_catalogue_examens_code
    ON catalogue_examens (code)
    WHERE code IS NOT NULL AND code <> '';

ALTER TABLE examens
    ADD COLUMN IF NOT EXISTS catalogue_id BIGINT REFERENCES catalogue_examens (id),
    ADD COLUMN IF NOT EXISTS acompte NUMERIC(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS dossier_statut VARCHAR(32) NOT NULL DEFAULT 'a_preparer',
    ADD COLUMN IF NOT EXISTS dossier_remis_at TIMESTAMP(6),
    ADD COLUMN IF NOT EXISTS dossier_remis_par VARCHAR(255),
    ADD COLUMN IF NOT EXISTS indication TEXT,
    ADD COLUMN IF NOT EXISTS technique TEXT,
    ADD COLUMN IF NOT EXISTS resultats TEXT,
    ADD COLUMN IF NOT EXISTS conclusion TEXT,
    ADD COLUMN IF NOT EXISTS passage_sans_rdv BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_examens_catalogue ON examens (catalogue_id);
CREATE INDEX IF NOT EXISTS idx_examens_dossier_statut ON examens (dossier_statut);

CREATE TABLE IF NOT EXISTS paiements_examen (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examen_id       BIGINT NOT NULL REFERENCES examens (id),
    montant         NUMERIC(10, 2) NOT NULL,
    mode            VARCHAR(32) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_paiements_examen ON paiements_examen (examen_id, created_at);

CREATE TABLE IF NOT EXISTS documents_examen (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examen_id       BIGINT REFERENCES examens (id),
    patient_id      BIGINT NOT NULL REFERENCES patients (id),
    type            VARCHAR(32) NOT NULL,
    nom_original    VARCHAR(255) NOT NULL,
    content_type    VARCHAR(128) NOT NULL,
    taille          BIGINT NOT NULL,
    storage_path    VARCHAR(512) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_documents_patient ON documents_examen (patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_documents_examen ON documents_examen (examen_id);
