-- Phase 1: resources (salles/machines) + appointments + status history.
-- Does not modify V1–V4. No seed data.

CREATE TABLE IF NOT EXISTS resources (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64)  NOT NULL,
    libelle         VARCHAR(255) NOT NULL,
    modalite        VARCHAR(32),
    actif           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_resources_code ON resources (code);

CREATE TABLE IF NOT EXISTS appointments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id          BIGINT NOT NULL REFERENCES patients (id),
    catalogue_id        BIGINT REFERENCES catalogue_examens (id),
    resource_id         BIGINT REFERENCES resources (id),
    prescripteur_id     BIGINT REFERENCES medecins_referents (id),
    examen_id           BIGINT REFERENCES examens (id),
    starts_at           TIMESTAMP(6) NOT NULL,
    ends_at             TIMESTAMP(6) NOT NULL,
    duree_minutes       INTEGER NOT NULL DEFAULT 30,
    modalite            VARCHAR(32) NOT NULL,
    priorite            VARCHAR(32) NOT NULL DEFAULT 'ROUTINE',
    statut              VARCHAR(32) NOT NULL DEFAULT 'SCHEDULED',
    motif               VARCHAR(512),
    notes               TEXT,
    cancelled_reason    VARCHAR(512),
    created_by_id       BIGINT REFERENCES utilisateurs (id),
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6),
    version             BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_appointments_starts ON appointments (starts_at);
CREATE INDEX IF NOT EXISTS idx_appointments_patient ON appointments (patient_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_appointments_resource ON appointments (resource_id, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_appointments_statut ON appointments (statut);
CREATE INDEX IF NOT EXISTS idx_appointments_examen ON appointments (examen_id);

CREATE TABLE IF NOT EXISTS appointment_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id  BIGINT NOT NULL REFERENCES appointments (id),
    from_statut     VARCHAR(32),
    to_statut       VARCHAR(32) NOT NULL,
    actor_id        BIGINT REFERENCES utilisateurs (id),
    note            VARCHAR(512),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_appt_status_hist
    ON appointment_status_history (appointment_id, created_at);
