-- Phase 4: versioned radiology reports.
-- Does not modify V1–V7. No DROP/TRUNCATE.

CREATE TABLE IF NOT EXISTS reports (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examen_id           BIGINT NOT NULL REFERENCES examens (id),
    status              VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    current_version     INTEGER NOT NULL DEFAULT 1,
    author_id           BIGINT REFERENCES utilisateurs (id),
    author_name         VARCHAR(255),
    validated_at        TIMESTAMP(6),
    validated_by_id     BIGINT REFERENCES utilisateurs (id),
    validated_by_name   VARCHAR(255),
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reports_examen ON reports (examen_id);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports (status);
CREATE INDEX IF NOT EXISTS idx_reports_created ON reports (created_at);

CREATE TABLE IF NOT EXISTS report_versions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id       BIGINT NOT NULL REFERENCES reports (id),
    version_number  INTEGER NOT NULL,
    indication      TEXT,
    technique       TEXT,
    resultats       TEXT,
    conclusion      TEXT,
    body            TEXT,
    author_id       BIGINT REFERENCES utilisateurs (id),
    author_name     VARCHAR(255),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_report_versions_num
    ON report_versions (report_id, version_number);
CREATE INDEX IF NOT EXISTS idx_report_versions_report
    ON report_versions (report_id, created_at);

CREATE TABLE IF NOT EXISTS report_validations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id       BIGINT NOT NULL REFERENCES reports (id),
    version_number  INTEGER NOT NULL,
    validator_id    BIGINT REFERENCES utilisateurs (id),
    validator_name  VARCHAR(255),
    validated_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_report_validations_report
    ON report_validations (report_id, validated_at);

CREATE TABLE IF NOT EXISTS report_amendments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id       BIGINT NOT NULL REFERENCES reports (id),
    from_version    INTEGER NOT NULL,
    to_version      INTEGER NOT NULL,
    reason          VARCHAR(1024) NOT NULL,
    author_id       BIGINT REFERENCES utilisateurs (id),
    author_name     VARCHAR(255),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_report_amendments_report
    ON report_amendments (report_id, created_at);

-- Backfill: examens with CR content or statut_cr in (signe, imprime, en_redaction)
INSERT INTO reports (
    examen_id,
    status,
    current_version,
    author_name,
    validated_at,
    validated_by_name,
    created_at,
    updated_at
)
SELECT
    e.id,
    CASE
        WHEN e.statut_cr IN ('signe', 'imprime') THEN 'VALIDATED'
        ELSE 'DRAFT'
    END,
    1,
    COALESCE(e.medecin, 'Migration'),
    CASE
        WHEN e.statut_cr IN ('signe', 'imprime') THEN COALESCE(e.updated_at, e.created_at, CURRENT_TIMESTAMP)
        ELSE NULL
    END,
    CASE
        WHEN e.statut_cr IN ('signe', 'imprime') THEN COALESCE(e.medecin, 'Migration')
        ELSE NULL
    END,
    COALESCE(e.created_at, CURRENT_TIMESTAMP),
    e.updated_at
FROM examens e
WHERE NOT EXISTS (SELECT 1 FROM reports r WHERE r.examen_id = e.id)
  AND (
        e.statut_cr IN ('signe', 'imprime', 'en_redaction')
        OR (e.compte_rendu IS NOT NULL AND TRIM(e.compte_rendu) <> '')
        OR (e.indication IS NOT NULL AND TRIM(e.indication) <> '')
        OR (e.technique IS NOT NULL AND TRIM(e.technique) <> '')
        OR (e.resultats IS NOT NULL AND TRIM(e.resultats) <> '')
        OR (e.conclusion IS NOT NULL AND TRIM(e.conclusion) <> '')
      );

INSERT INTO report_versions (
    report_id,
    version_number,
    indication,
    technique,
    resultats,
    conclusion,
    body,
    author_name,
    created_at
)
SELECT
    r.id,
    1,
    e.indication,
    e.technique,
    e.resultats,
    e.conclusion,
    e.compte_rendu,
    COALESCE(r.author_name, e.medecin, 'Migration'),
    COALESCE(e.created_at, CURRENT_TIMESTAMP)
FROM reports r
JOIN examens e ON e.id = r.examen_id
WHERE NOT EXISTS (
    SELECT 1 FROM report_versions rv WHERE rv.report_id = r.id AND rv.version_number = 1
);

INSERT INTO report_validations (
    report_id,
    version_number,
    validator_name,
    validated_at
)
SELECT
    r.id,
    1,
    COALESCE(r.validated_by_name, r.author_name, 'Migration'),
    COALESCE(r.validated_at, CURRENT_TIMESTAMP)
FROM reports r
WHERE r.status = 'VALIDATED'
  AND NOT EXISTS (SELECT 1 FROM report_validations v WHERE v.report_id = r.id);
