-- Phase 5: invoices / payments / refunds. Does not modify V1–V8.

CREATE TABLE IF NOT EXISTS invoices (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(64)  NOT NULL,
    patient_id          BIGINT NOT NULL REFERENCES patients (id),
    statut              VARCHAR(32)  NOT NULL DEFAULT 'DRAFT',
    total               NUMERIC(12, 2) NOT NULL DEFAULT 0,
    amount_paid         NUMERIC(12, 2) NOT NULL DEFAULT 0,
    amount_refunded     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    insurance_share     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    patient_share       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    remise              NUMERIC(12, 2) NOT NULL DEFAULT 0,
    mode_paiement       VARCHAR(32),
    notes               TEXT,
    created_by_id       BIGINT REFERENCES utilisateurs (id),
    created_by_name     VARCHAR(255),
    issued_at           TIMESTAMP(6),
    cancelled_at        TIMESTAMP(6),
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6),
    version             BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_invoices_reference ON invoices (reference);
CREATE INDEX IF NOT EXISTS idx_invoices_patient ON invoices (patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_statut ON invoices (statut);

CREATE TABLE IF NOT EXISTS invoice_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          BIGINT NOT NULL REFERENCES invoices (id),
    examen_id           BIGINT REFERENCES examens (id),
    catalogue_id        BIGINT REFERENCES catalogue_examens (id),
    label               VARCHAR(512) NOT NULL,
    quantity            NUMERIC(10, 2) NOT NULL DEFAULT 1,
    unit_price          NUMERIC(12, 2) NOT NULL DEFAULT 0,
    line_total          NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice ON invoice_items (invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_items_examen ON invoice_items (examen_id);

CREATE TABLE IF NOT EXISTS payments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          BIGINT NOT NULL REFERENCES invoices (id),
    montant             NUMERIC(12, 2) NOT NULL,
    mode                VARCHAR(32) NOT NULL DEFAULT 'especes',
    idempotency_key     VARCHAR(128),
    created_by_id       BIGINT REFERENCES utilisateurs (id),
    created_by_name     VARCHAR(255),
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payments_idempotency
    ON payments (idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payments_invoice ON payments (invoice_id, created_at);

CREATE TABLE IF NOT EXISTS refunds (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          BIGINT NOT NULL REFERENCES invoices (id),
    montant             NUMERIC(12, 2) NOT NULL,
    reason              VARCHAR(512) NOT NULL,
    created_by_id       BIGINT REFERENCES utilisateurs (id),
    created_by_name     VARCHAR(255),
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_refunds_invoice ON refunds (invoice_id, created_at);
