/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FacturationRouteImport } from './routes/facturation'
import { Route as ImagerieRouteImport } from './routes/imagerie'
import { Route as MedecinsRouteImport } from './routes/medecins'
import { Route as MedecinsReferentsRouteImport } from './routes/medecins-referents'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as PatientDemoRouteImport } from './routes/patient.demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturationRoute = FacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagerieRoute = ImagerieRouteImport.update({
  id: '/imagerie',
  path: '/imagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const MedecinsRoute = MedecinsRouteImport.update({
  id: '/medecins',
  path: '/medecins',
  getParentRoute: () => rootRouteImport,
} as any)
const MedecinsReferentsRoute = MedecinsReferentsRouteImport.update({
  id: '/medecins-referents',
  path: '/medecins-referents',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDemoRoute = PatientDemoRouteImport.update({
  id: '/patient/demo',
  path: '/patient/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/facturation': typeof FacturationRoute
  '/imagerie': typeof ImagerieRoute
  '/medecins': typeof MedecinsRoute
  '/medecins-referents': typeof MedecinsReferentsRoute
  '/patients': typeof PatientsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viewer': typeof ViewerRoute
  '/whatsapp': typeof WhatsappRoute
  '/patient/demo': typeof PatientDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/facturation': typeof FacturationRoute
  '/imagerie': typeof ImagerieRoute
  '/medecins': typeof MedecinsRoute
  '/medecins-referents': typeof MedecinsReferentsRoute
  '/patients': typeof PatientsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viewer': typeof ViewerRoute
  '/whatsapp': typeof WhatsappRoute
  '/patient/demo': typeof PatientDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/facturation': typeof FacturationRoute
  '/imagerie': typeof ImagerieRoute
  '/medecins': typeof MedecinsRoute
  '/medecins-referents': typeof MedecinsReferentsRoute
  '/patients': typeof PatientsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viewer': typeof ViewerRoute
  '/whatsapp': typeof WhatsappRoute
  '/patient/demo': typeof PatientDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/chat'
    | '/dashboard'
    | '/facturation'
    | '/imagerie'
    | '/medecins'
    | '/medecins-referents'
    | '/patients'
    | '/sitemap.xml'
    | '/viewer'
    | '/whatsapp'
    | '/patient/demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/chat'
    | '/dashboard'
    | '/facturation'
    | '/imagerie'
    | '/medecins'
    | '/medecins-referents'
    | '/patients'
    | '/sitemap.xml'
    | '/viewer'
    | '/whatsapp'
    | '/patient/demo'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/chat'
    | '/dashboard'
    | '/facturation'
    | '/imagerie'
    | '/medecins'
    | '/medecins-referents'
    | '/patients'
    | '/sitemap.xml'
    | '/viewer'
    | '/whatsapp'
    | '/patient/demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  FacturationRoute: typeof FacturationRoute
  ImagerieRoute: typeof ImagerieRoute
  MedecinsRoute: typeof MedecinsRoute
  MedecinsReferentsRoute: typeof MedecinsReferentsRoute
  PatientsRoute: typeof PatientsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ViewerRoute: typeof ViewerRoute
  WhatsappRoute: typeof WhatsappRoute
  PatientDemoRoute: typeof PatientDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturation': {
      id: '/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof FacturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagerie': {
      id: '/imagerie'
      path: '/imagerie'
      fullPath: '/imagerie'
      preLoaderRoute: typeof ImagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medecins': {
      id: '/medecins'
      path: '/medecins'
      fullPath: '/medecins'
      preLoaderRoute: typeof MedecinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medecins-referents': {
      id: '/medecins-referents'
      path: '/medecins-referents'
      fullPath: '/medecins-referents'
      preLoaderRoute: typeof MedecinsReferentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/demo': {
      id: '/patient/demo'
      path: '/patient/demo'
      fullPath: '/patient/demo'
      preLoaderRoute: typeof PatientDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  FacturationRoute: FacturationRoute,
  ImagerieRoute: ImagerieRoute,
  MedecinsRoute: MedecinsRoute,
  MedecinsReferentsRoute: MedecinsReferentsRoute,
  PatientsRoute: PatientsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ViewerRoute: ViewerRoute,
  WhatsappRoute: WhatsappRoute,
  PatientDemoRoute: PatientDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
