/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as FacturationRouteImport } from './routes/facturation'
import { Route as ImagerieRouteImport } from './routes/imagerie'
import { Route as MedecinsRouteImport } from './routes/medecins'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as WhatsappRouteImport } from './routes/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturationRoute = FacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagerieRoute = ImagerieRouteImport.update({
  id: '/imagerie',
  path: '/imagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const MedecinsRoute = MedecinsRouteImport.update({
  id: '/medecins',
  path: '/medecins',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/facturation': typeof FacturationRoute
  '/imagerie': typeof ImagerieRoute
  '/medecins': typeof MedecinsRoute
  '/patients': typeof PatientsRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/facturation': typeof FacturationRoute
  '/imagerie': typeof ImagerieRoute
  '/medecins': typeof MedecinsRoute
  '/patients': typeof PatientsRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/facturation': typeof FacturationRoute
  '/imagerie': typeof ImagerieRoute
  '/medecins': typeof MedecinsRoute
  '/patients': typeof PatientsRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/facturation'
    | '/imagerie'
    | '/medecins'
    | '/patients'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/facturation'
    | '/imagerie'
    | '/medecins'
    | '/patients'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/facturation'
    | '/imagerie'
    | '/medecins'
    | '/patients'
    | '/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  FacturationRoute: typeof FacturationRoute
  ImagerieRoute: typeof ImagerieRoute
  MedecinsRoute: typeof MedecinsRoute
  PatientsRoute: typeof PatientsRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturation': {
      id: '/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof FacturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagerie': {
      id: '/imagerie'
      path: '/imagerie'
      fullPath: '/imagerie'
      preLoaderRoute: typeof ImagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medecins': {
      id: '/medecins'
      path: '/medecins'
      fullPath: '/medecins'
      preLoaderRoute: typeof MedecinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  FacturationRoute: FacturationRoute,
  ImagerieRoute: ImagerieRoute,
  MedecinsRoute: MedecinsRoute,
  PatientsRoute: PatientsRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
