/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccueilRouteImport } from './routes/accueil'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ComptesRendusRouteImport } from './routes/comptes-rendus'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DonneesRouteImport } from './routes/donnees'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as FacturationRouteImport } from './routes/facturation'
import { Route as FileAttenteRouteImport } from './routes/file-attente'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ImagerieRouteImport } from './routes/imagerie'
import { Route as ImpayesRouteImport } from './routes/impayes'
import { Route as MedecinsRouteImport } from './routes/medecins'
import { Route as MedecinsReferentsRouteImport } from './routes/medecins-referents'
import { Route as NumerisationRouteImport } from './routes/numerisation'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as WorklistRouteImport } from './routes/worklist'
import { Route as PatientPatientIdRouteImport } from './routes/patient.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesRendusRoute = ComptesRendusRouteImport.update({
  id: '/comptes-rendus',
  path: '/comptes-rendus',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonneesRoute = DonneesRouteImport.update({
  id: '/donnees',
  path: '/donnees',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturationRoute = FacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => rootRouteImport,
} as any)
const FileAttenteRoute = FileAttenteRouteImport.update({
  id: '/file-attente',
  path: '/file-attente',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagerieRoute = ImagerieRouteImport.update({
  id: '/imagerie',
  path: '/imagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpayesRoute = ImpayesRouteImport.update({
  id: '/impayes',
  path: '/impayes',
  getParentRoute: () => rootRouteImport,
} as any)
const MedecinsRoute = MedecinsRouteImport.update({
  id: '/medecins',
  path: '/medecins',
  getParentRoute: () => rootRouteImport,
} as any)
const MedecinsReferentsRoute = MedecinsReferentsRouteImport.update({
  id: '/medecins-referents',
  path: '/medecins-referents',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerisationRoute = NumerisationRouteImport.update({
  id: '/numerisation',
  path: '/numerisation',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const WorklistRoute = WorklistRouteImport.update({
  id: '/worklist',
  path: '/worklist',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPatientIdRoute = PatientPatientIdRouteImport.update({
  id: '/patient/$patientId',
  path: '/patient/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/catalogue': typeof CatalogueRoute
  '/chat': typeof ChatRoute
  '/comptes-rendus': typeof ComptesRendusRoute
  '/dashboard': typeof DashboardRoute
  '/donnees': typeof DonneesRoute
  '/dossiers': typeof DossiersRoute
  '/facturation': typeof FacturationRoute
  '/file-attente': typeof FileAttenteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/imagerie': typeof ImagerieRoute
  '/impayes': typeof ImpayesRoute
  '/medecins': typeof MedecinsRoute
  '/medecins-referents': typeof MedecinsReferentsRoute
  '/numerisation': typeof NumerisationRoute
  '/parametres': typeof ParametresRoute
  '/patients': typeof PatientsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viewer': typeof ViewerRoute
  '/whatsapp': typeof WhatsappRoute
  '/worklist': typeof WorklistRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/catalogue': typeof CatalogueRoute
  '/chat': typeof ChatRoute
  '/comptes-rendus': typeof ComptesRendusRoute
  '/dashboard': typeof DashboardRoute
  '/donnees': typeof DonneesRoute
  '/dossiers': typeof DossiersRoute
  '/facturation': typeof FacturationRoute
  '/file-attente': typeof FileAttenteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/imagerie': typeof ImagerieRoute
  '/impayes': typeof ImpayesRoute
  '/medecins': typeof MedecinsRoute
  '/medecins-referents': typeof MedecinsReferentsRoute
  '/numerisation': typeof NumerisationRoute
  '/parametres': typeof ParametresRoute
  '/patients': typeof PatientsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viewer': typeof ViewerRoute
  '/whatsapp': typeof WhatsappRoute
  '/worklist': typeof WorklistRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/catalogue': typeof CatalogueRoute
  '/chat': typeof ChatRoute
  '/comptes-rendus': typeof ComptesRendusRoute
  '/dashboard': typeof DashboardRoute
  '/donnees': typeof DonneesRoute
  '/dossiers': typeof DossiersRoute
  '/facturation': typeof FacturationRoute
  '/file-attente': typeof FileAttenteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/imagerie': typeof ImagerieRoute
  '/impayes': typeof ImpayesRoute
  '/medecins': typeof MedecinsRoute
  '/medecins-referents': typeof MedecinsReferentsRoute
  '/numerisation': typeof NumerisationRoute
  '/parametres': typeof ParametresRoute
  '/patients': typeof PatientsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viewer': typeof ViewerRoute
  '/whatsapp': typeof WhatsappRoute
  '/worklist': typeof WorklistRoute
  '/patient/$patientId': typeof PatientPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accueil'
    | '/agenda'
    | '/analytics'
    | '/audit'
    | '/catalogue'
    | '/chat'
    | '/comptes-rendus'
    | '/dashboard'
    | '/donnees'
    | '/dossiers'
    | '/facturation'
    | '/file-attente'
    | '/forgot-password'
    | '/imagerie'
    | '/impayes'
    | '/medecins'
    | '/medecins-referents'
    | '/numerisation'
    | '/parametres'
    | '/patients'
    | '/reset-password'
    | '/sitemap.xml'
    | '/viewer'
    | '/whatsapp'
    | '/worklist'
    | '/patient/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accueil'
    | '/agenda'
    | '/analytics'
    | '/audit'
    | '/catalogue'
    | '/chat'
    | '/comptes-rendus'
    | '/dashboard'
    | '/donnees'
    | '/dossiers'
    | '/facturation'
    | '/file-attente'
    | '/forgot-password'
    | '/imagerie'
    | '/impayes'
    | '/medecins'
    | '/medecins-referents'
    | '/numerisation'
    | '/parametres'
    | '/patients'
    | '/reset-password'
    | '/sitemap.xml'
    | '/viewer'
    | '/whatsapp'
    | '/worklist'
    | '/patient/$patientId'
  id:
    | '__root__'
    | '/'
    | '/accueil'
    | '/agenda'
    | '/analytics'
    | '/audit'
    | '/catalogue'
    | '/chat'
    | '/comptes-rendus'
    | '/dashboard'
    | '/donnees'
    | '/dossiers'
    | '/facturation'
    | '/file-attente'
    | '/forgot-password'
    | '/imagerie'
    | '/impayes'
    | '/medecins'
    | '/medecins-referents'
    | '/numerisation'
    | '/parametres'
    | '/patients'
    | '/reset-password'
    | '/sitemap.xml'
    | '/viewer'
    | '/whatsapp'
    | '/worklist'
    | '/patient/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccueilRoute: typeof AccueilRoute
  AgendaRoute: typeof AgendaRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  CatalogueRoute: typeof CatalogueRoute
  ChatRoute: typeof ChatRoute
  ComptesRendusRoute: typeof ComptesRendusRoute
  DashboardRoute: typeof DashboardRoute
  DonneesRoute: typeof DonneesRoute
  DossiersRoute: typeof DossiersRoute
  FacturationRoute: typeof FacturationRoute
  FileAttenteRoute: typeof FileAttenteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImagerieRoute: typeof ImagerieRoute
  ImpayesRoute: typeof ImpayesRoute
  MedecinsRoute: typeof MedecinsRoute
  MedecinsReferentsRoute: typeof MedecinsReferentsRoute
  NumerisationRoute: typeof NumerisationRoute
  ParametresRoute: typeof ParametresRoute
  PatientsRoute: typeof PatientsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ViewerRoute: typeof ViewerRoute
  WhatsappRoute: typeof WhatsappRoute
  WorklistRoute: typeof WorklistRoute
  PatientPatientIdRoute: typeof PatientPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes-rendus': {
      id: '/comptes-rendus'
      path: '/comptes-rendus'
      fullPath: '/comptes-rendus'
      preLoaderRoute: typeof ComptesRendusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donnees': {
      id: '/donnees'
      path: '/donnees'
      fullPath: '/donnees'
      preLoaderRoute: typeof DonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturation': {
      id: '/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof FacturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-attente': {
      id: '/file-attente'
      path: '/file-attente'
      fullPath: '/file-attente'
      preLoaderRoute: typeof FileAttenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagerie': {
      id: '/imagerie'
      path: '/imagerie'
      fullPath: '/imagerie'
      preLoaderRoute: typeof ImagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impayes': {
      id: '/impayes'
      path: '/impayes'
      fullPath: '/impayes'
      preLoaderRoute: typeof ImpayesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medecins': {
      id: '/medecins'
      path: '/medecins'
      fullPath: '/medecins'
      preLoaderRoute: typeof MedecinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medecins-referents': {
      id: '/medecins-referents'
      path: '/medecins-referents'
      fullPath: '/medecins-referents'
      preLoaderRoute: typeof MedecinsReferentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerisation': {
      id: '/numerisation'
      path: '/numerisation'
      fullPath: '/numerisation'
      preLoaderRoute: typeof NumerisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worklist': {
      id: '/worklist'
      path: '/worklist'
      fullPath: '/worklist'
      preLoaderRoute: typeof WorklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$patientId': {
      id: '/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof PatientPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccueilRoute: AccueilRoute,
  AgendaRoute: AgendaRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  CatalogueRoute: CatalogueRoute,
  ChatRoute: ChatRoute,
  ComptesRendusRoute: ComptesRendusRoute,
  DashboardRoute: DashboardRoute,
  DonneesRoute: DonneesRoute,
  DossiersRoute: DossiersRoute,
  FacturationRoute: FacturationRoute,
  FileAttenteRoute: FileAttenteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImagerieRoute: ImagerieRoute,
  ImpayesRoute: ImpayesRoute,
  MedecinsRoute: MedecinsRoute,
  MedecinsReferentsRoute: MedecinsReferentsRoute,
  NumerisationRoute: NumerisationRoute,
  ParametresRoute: ParametresRoute,
  PatientsRoute: PatientsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ViewerRoute: ViewerRoute,
  WhatsappRoute: WhatsappRoute,
  WorklistRoute: WorklistRoute,
  PatientPatientIdRoute: PatientPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
